/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Mon Feb 08 18:04:35 2021
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


